"""State manager to mutate, persist, and broadcast agent session states."""

from datetime import UTC, datetime

from vera_engine.core.entities import (
    AgentState,
    Capability,
    Event,
    ProjectMetadata,
    Task,
    TaskStatus,
)
from vera_engine.core.interfaces.repository import SessionRepository
from vera_engine.runtime.events import EventDispatcher


class StateManager:
    """Manages mutations on the AgentState.

    Persists updates and broadcasts events to the system.
    """

    def __init__(
        self,
        session_id: str,
        goal: str,
        workflow: str,
        repository: SessionRepository,
        dispatcher: EventDispatcher,
        capabilities: list[Capability] | None = None,
    ) -> None:
        """Initializes the state manager, creates the initial state, and saves it.

        Args:
            session_id: Unique identifier for the agent session.
            goal: The primary goal for the agent.
            workflow: The active workflow name.
            repository: The persistence adapter for saving state snapshots.
            dispatcher: The event dispatcher for broadcasting updates.
            capabilities: Optional list of high-level capabilities.
        """
        self._repository = repository
        self._dispatcher = dispatcher

        # Create initial state representation
        self._state = AgentState(
            session_id=session_id,
            goal=goal,
            current_workflow=workflow,
            capabilities=capabilities or [],
        )

        # Persist and dispatch initialization event
        self._persist_and_broadcast("SessionStarted")

    @property
    def state(self) -> AgentState:
        """Returns a read-only snapshot copy of the current state."""
        return self._state.model_copy(deep=True)

    def update_tasks(self, tasks: list[Task]) -> None:
        """Sets the tasks generated by the planning phase.

        Args:
            tasks: The decomposed list of tasks to execute.
        """
        self._state.tasks = tasks
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast("PlanCreated", {"tasks_count": len(tasks)})

    def start_task(self, task_id: str) -> None:
        """Transitions a task status to IN_PROGRESS.

        Args:
            task_id: The ID of the task to start.
        """
        for task in self._state.tasks:
            if task.id == task_id:
                task.status = TaskStatus.IN_PROGRESS
                break
        self._state.current_task_id = task_id
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast("TaskStarted", {"task_id": task_id})

    def complete_task(self, task_id: str, result: str) -> None:
        """Transitions a task status to COMPLETED and stores its result.

        Args:
            task_id: The ID of the completed task.
            result: The output string result of the task execution.
        """
        for task in self._state.tasks:
            if task.id == task_id:
                task.status = TaskStatus.COMPLETED
                task.execution_result = result
                break
        self._state.current_task_id = None
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast(
            "TaskCompleted", {"task_id": task_id, "success": True}
        )

    def fail_task(self, task_id: str, error: str) -> None:
        """Transitions a task status to FAILED and stores the error message.

        Args:
            task_id: The ID of the failed task.
            error: The error message explaining the failure.
        """
        for task in self._state.tasks:
            if task.id == task_id:
                task.status = TaskStatus.FAILED
                task.execution_result = error
                break
        self._state.current_task_id = None
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast("TaskFailed", {"task_id": task_id, "error": error})

    def set_running_tool(self, tool_name: str | None) -> None:
        """Updates the active tool currently running in the executor.

        Args:
            tool_name: The name of the tool, or None if no tool is running.
        """
        self._state.running_tool = tool_name
        self._state.updated_at = datetime.now(UTC)
        if tool_name:
            self._persist_and_broadcast("ToolSelected", {"tool_name": tool_name})
        else:
            self._persist_and_broadcast("ToolCleared")

    def update_project_metadata(self, metadata: ProjectMetadata) -> None:
        """Sets the discovered project structure metadata and persists the state.

        Args:
            metadata: The compiled project metadata entity.
        """
        self._state.project_metadata = metadata
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast("DiscoveryCompleted")

    def finalize_session(self, summary: str, success: bool) -> None:
        """Marks the session as completed and sets success flags and summaries.

        Args:
            summary: The final execution summary text.
            success: Whether the user goal was successfully met.
        """
        self._state.is_completed = True
        self._state.success = success
        self._state.summary = summary
        self._state.updated_at = datetime.now(UTC)
        self._persist_and_broadcast(
            "SessionFinalized", {"success": success, "summary": summary}
        )

    def _persist_and_broadcast(
        self, event_name: str, payload_data: dict | None = None
    ) -> None:
        """Internal helper to save state to the repository and dispatch events."""
        # Save state snapshot
        self._repository.save_state(self._state)

        # Broadcast event
        payload = {"session_id": self._state.session_id}
        if payload_data:
            payload.update(payload_data)

        event = Event(name=event_name, payload=payload)
        self._dispatcher.dispatch(event)
